# Site settings
title: Strike7 ad
email: your-email@domain.com
description: > # thiadvertisement general generator
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  strike7

# Build settings
markdown: kramdown


collections:
  grupos:
    output: true
    permalink: /grupo/:path/
  jogos:
    output: true
    permalink: /mercado/:path/
